### ISSUE TITLE
strange speed reeding from tacx vortex

### ISSUE THREAD

**Issue by m1588** [GoldenCheetah/GoldenCheetah#1915]
There are strange speed reedings found in the recording of the workout data made with GC train mode.
The data comes from Tacx Vortex trainer connected via and dongle on OS X 10.11 system.
Everything is fine with the power setting/reading and cadence as well as HR data from wahoo Tickr. However the speed value is fluctating periodacaly from about 30 at one second to 15 in the next one returning to 30 just after that.
Please find the screenshot of the exact workout data attached. 
Is it possible to log the data exactly as they come from the trainer (to figure out if the data comes incorrect from the trainer or the issue is in the GC code).
<img width="621" alt="screen shot 2016-04-03 at 10 38 53" src="https://cloud.githubusercontent.com/assets/17220939/14231351/f1a81352-f988-11e5-8040-ee881778cd45.png">

Thanks.

**Comment by liversedge** [comment]
This is fixed in v4.

**Comment by m1588** [comment]
Actually this workout was captured with the 1603 build of the 4.0 version.

**Comment by liversedge** [comment]
Do you have a S+C sensor enabled?

**Comment by m1588** [comment]
nope, the sensor im has BTLE connectivity only.
So, in GC the trainer configuration looks like this:

<img width="408" alt="screen shot 2016-04-04 at 19 56 19" src="https://cloud.githubusercontent.com/assets/17220939/14255942/55b2caf6-fa9f-11e5-8d4a-15c77a8f0a61.png">

**Comment by tiagovarela** [comment]
I'm still experiencing this bug on the latest dev build (3941).
Trainer: Tacx Vortex Smart (ANT Power, Speed and Cadence)
OS: OSX 10.11.4

I saved the `antlog` from an activity where this happened (older build: 3940). [antlog.zip](https://github.com/GoldenCheetah/GoldenCheetah/files/266229/antlog.zip)

Let me know if you need further debugging files. :)

**Comment by Jagdfalke** [comment]
How did you pair the trainer? Did you set the speed channel unused? 

Note that power, speed, and cadence are all broadcast via the FE-C channel, so this is the only channel you need to use. 

If you are not sure whether you used the speed channel or not, try re-pairing the trainer and only selecting the FE-C channel.

**Comment by tiagovarela** [comment]
I had Power and Speed+Cadence selected from the trainer.

Using just the FE-C channel works!

Is there a way to connect this trainer without using only the FE-C channel? Or use the FE-C channel without enforcing power target? (Some workouts do not call for GC to control the trainer)
