### ISSUE TITLE
Strava sync issue (dev build 1903)

### ISSUE THREAD

**Issue by suskozaver** [GoldenCheetah/GoldenCheetah#3122]
Does anyone else have an issue (using dev build 1903) that every 30 days (estimate), when I try to sync with Strava (I only download the activities) it shows like a month of activities, but not today's. 
And it stays that way (adding the missing days each day), unless I go into Options, Athlete, Accounts, Edit Strava account and re-authorize it. 
And this happens monthly for me.

**Comment by doubledadster** [comment]
Yes.  On Dev Build 1903, from time to time GC selects (incorrectly) activities for upload to Strava.  My last download from Strava was Nov 6, this morning, GC will not select any activities from Strava for download.  I have re-authorized Strava without success.  I wonder if Strava's API has changed.

**Comment by amtriathlon** [comment]
If you look at goldencheetah.log parallel to your athlete's folder you will likely find:
`error "Host requires authentication"
`
This indicates the authorization token you have is no longer valid and you need to reauthorize using their updated OAuth process, this is fixed in source but it will be generally available in the next build. 
More details in https://github.com/GoldenCheetah/GoldenCheetah/issues/3199

**Comment by doubledadster** [comment]
I am still having an issue despite removing strava from the cloud services, deleting the token from the athlete-private.ini file, removing GC from my strava account, and re-authorizing strava.  See attached files.  The error is "Host requires authentication" in the log. What am I missing?

[goldencheetah.log](https://github.com/GoldenCheetah/GoldenCheetah/files/3852783/goldencheetah.log)

**Comment by amtriathlon** [comment]
The need to wait for a new GC build including the fix mentioned in my previous answer.
